package org.paramanuseniorshealth.notices

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import org.paramanuseniorshealth.notices.activation.ActivationCode

/**
 * Cross-implementation check between the Kotlin validator and the JavaScript generator in
 * `docs/apps-script/Code.gs`.
 *
 * The two implement the same check-character rule in different languages. If they ever drift, every
 * slip printed by the console is rejected on every phone, with an error message that blames the
 * user for mistyping. That failure would be discovered at a dispensary counter by someone in their
 * eighties, which is the worst possible place to discover it.
 *
 * These codes were produced by the Apps Script generator and pasted here verbatim. Regenerate and
 * replace them if the algorithm is ever deliberately changed; do not "fix" them by hand.
 */
class GeneratedCodeCompatibilityTest {

    private val generatedByAppsScript = listOf(
        "P1AYREVQ",   // reserved for Play review
        "Y4EJ65B1",
        "THHVWEHJ",
        "MQCAMGPC",
        "NQX18XAT",
        "XE29ND28",
        "AP4R172Z",
        "7B23AFX6",
        "GR9G36QF",
        "16MN3D3F",
        "QSPP3X8R",
    )

    @Test
    fun `every code the generator produced is accepted by the app`() {
        for (code in generatedByAppsScript) {
            assertTrue("$code was generated by the console but rejected by the app", ActivationCode.isValid(code))
        }
    }

    @Test
    fun `generated codes use only the Crockford alphabet`() {
        for (code in generatedByAppsScript) {
            for (ch in code) {
                assertTrue("$code contains '$ch', which is not in the alphabet", ch in ActivationCode.ALPHABET)
            }
        }
    }

    @Test
    fun `corrupting a generated code makes it invalid`() {
        // Confirms the codes above pass because the check character is right, not because the
        // validator accepts anything of the correct length.
        for (code in generatedByAppsScript) {
            val corrupted = code.dropLast(1) + if (code.last() == '0') '1' else '0'
            assertFalse("$corrupted should not validate", ActivationCode.isValid(corrupted))
        }
    }
}
